### PR TITLE
Updated to 4.6, added Init dialog.

### PR DESCRIPTION
**Pull request by sturnclaw**
TArray<>::FindMatch is deprecated in 4.6.  It is replaced by [IndexOfByPredicate()](https://docs.unrealengine.com/latest/INT/API/Runtime/Core/Containers/TArray/IndexOfByPredicate/index.html).  Unfortunately, I do not possess the required knowledge to make the transition, so I settled for a todo notice in the code.

Updated and compiled for UE4 4.6.0.

### CODE REVIEW

**Comment by SRombauts** [comment]
Hi @Web-eWorks,

Just to let you know:

I have given my plugin to Epic Games for integration into the upcoming 4.7
But for re-license clarity, I have removed all the code I was not the author, so the init dialog was stripped off :(

Now you can make a similar Pull Request directly to EpicGames. 

Cheers!

**Comment by SRombauts** [comment]
Hi, 

I believe everything will be clear while UE4.7 will be out. They will explain this! 

But there will be no download, it will be integrated by default. You will only have to select it on the list of source control. 
Only at first it will be marked 'experimental' so there will be an option to tick on a menu.

also you will have to remove my plugin from your project to avoid a clash.

**Comment by MikeFricker** [comment]
I think what we're going to do actually is enable the plugin by default in 4.7, but put a "Beta!" warning right next to it in the dropdown list where you select your source control provider.  We did leave the plugin marked as "Beta" as well, but thought it was more discoverable if it was enabled by default.  So as of yesterday that's how we've set it up in the 4.7 branch.  We'll see as we get further along with QA testing.

**Comment by SRombauts** [comment]
Nice! Will be easier for newcomers :)

**Pull request merged**
