### PR TITLE
Stop tracking the Git plugin DLL

### PR DESCRIPTION
**Pull request by sinbad**
You might not want to merge this one, but I've submitted it for your consideration. 

Tracking the DLL in the repo means that if you use this plugin as a submodule inside your project (and including it inside your project is the only supported way right now), it's always considered modified and makes your `git status` unclean, because the plugin is always built by UBT.

I appreciate that if you just use the ZIP version of the repo this isn't necessarily an issue, and having the DLL prebuilt is likely convenient for many people. Hence you might not want to merge this, it's just a change I've made in my own fork to clean things up when using it as a submodule (my preferred way since I can track changes & submit them more easily)

### CODE REVIEW

**Comment by SRombauts** [comment]
I could merge the gitignore part and keep the dll in.
This way I would still be able to submit the binary version, and you should see the repo clean

**Comment by sinbad** [comment]
I don’t think that will work, the gitignore only hides files that are no added, it doesn’t ignore changes to files that are tracked.

**Comment by sinbad** [comment]
> I don’t think that will work, the gitignore only hides files that are not yet added, it doesn’t ignore changes to files that are tracked.

Yeah, confirmed: turns out the *.modules files are already ignored but UE4Editor.modules was tracked in this repo and had the same problem, the buildID can change when you rebuild your project and make the submodule dirty that way as well. I've added  untracking UE4Editor.modules to this "fix".

**Comment by SRombauts** [comment]
Thanks for the suggestion :)
It might be the best way going forward, but for now I'll let it like it is and reconsider next time I spend enough time developing with the plugin

**Pull request closed without merging**
